# TMUX FTW!
set -g prefix C-a
unbind C-b

setw -g mouse on

set -g default-terminal "tmux-256color"

set-option -g status-position top
set -g history-limit 50000
set -g base-index 1

# switch panes using Alt-arrow without prefix
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
#bind -n C-M-Left swap-window -t -1
#bind -n C-M-Right swap-window -t +1

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity on
set -g visual-bell on
set -g visual-silence off
setw -g monitor-activity on
#set -g bell-action none

# clock mode
#setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=yellow bg=red bold'

# TMUX PLUGIN MANAGER
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @treemux-tree-client 'nvim-tree'  # or 'neo-tree'
set -g @treemux-tree-nvim-init-file '~/.tmux/plugins/treemux/configs/treemux_init.lua'
set -g @plugin 'kiyoon/treemux'

# CATPPUCIN THEME
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"

# STATUS BAR
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

set -g @batt_icon_charge_tier8 '🌕'
set -g @batt_icon_charge_tier7 '🌖'
set -g @batt_icon_charge_tier6 '🌖'
set -g @batt_icon_charge_tier5 '🌗'
set -g @batt_icon_charge_tier4 '🌗'
set -g @batt_icon_charge_tier3 '🌘'
set -g @batt_icon_charge_tier2 '🌘'
set -g @batt_icon_charge_tier1 '🌑'
set -g @batt_icon_status_charged '🔋'
set -g @batt_icon_status_charging '⚡'
set -g @batt_icon_status_discharging '👎'
set -g @batt_color_status_primary_charged '#3daee9'
set -g @batt_color_status_primary_charging '#3daee9'


set -g @tmux_window_name_shells "['bash', 'fish', 'sh', 'zsh']"
set -g @tmux_window_dir_programs "['nvim', 'vim', 'vi', 'git']"

set -g @tmux_window_name_max_name_len "20"
set -g @tmux_window_name_icon_style "'name_and_icon'"

# Custom icons example
set -g @tmux_window_name_custom_icons '{"python": "🐍", "custom_app": "📦"}'


# SESH CONFIG
bind-key "K" display-popup -E -w 40% "sesh connect \"$(
  sesh list -i | gum filter --limit 1 --placeholder 'Pick a sesh' --prompt='⚡'
)\""

bind-key "J" run-shell "sesh connect \"$(
  sesh list -i | fzf-tmux --ansi -p 55%,60% \
    --no-sort --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^x zoxide ^g config ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list -i)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -it)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -ic)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -iz)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""



# run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'  # Using config location for now

# Initialize TMUX plugin manager
# ***keep this line at the very bottom of tmux.conf***
run '~/.tmux/plugins/tpm/tpm'
